spring.application.name=sensor-backend
server.port=${PORT:8080}

# PostgreSQL Bağlantı Ayarları (Railway ortam değişkenleri kullanılarak)
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# Hibernate / JPA Ayarları (Tabloları otomatik oluşturması için)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true